VAGRANTFILE_API_VERSION = '2'

  Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "ubuntu-16.04"
  
    # VM
    config.vm.define :'host1' do |host|
      host.vm.hostname = 'host1'
      host.vm.network :forwarded_port, guest: 22, host: 2001, id: "ssh"
      host.vm.network :private_network, ip: "192.168.100.11"
    end
 
    config.vm.define :'host2' do |host|
      host.vm.hostname = 'host2'
      host.vm.network :forwarded_port, guest: 22, host: 2002, id: "ssh"
      host.vm.network :forwarded_port, guest: 80, host: 8000, id: "http"
      host.vm.network :private_network, ip: "192.168.100.12"
    end
 
    config.vbguest.auto_update = false
  end
