---
- name: nginxの起動ユーザーの追加
  user:
    name: nginx

- name: nginxのインストール
  apt:
    name: nginx
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: nginxのサービススタート
  service:
    name: nginx
    enabled: yes

- name: nginx設定ファイルの設置
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default

- name: nginx本体の設定ファイルを変更
  template:
    src: n.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx
